image: python:latest

stages:
  - test

test:
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python manage.py test
  only:
    - master